services:
  - type: web
    name: voter-management-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 600 --workers 1 --worker-class sync --max-requests 10 --max-requests-jitter 2 --keep-alive 15 --preload-app --bind 0.0.0.0:$PORT wsgi:app
    region: oregon
    pythonVersion: '3.11'
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: ""