services:
  - type: web
    name: voter-management-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    region: oregon
    pythonVersion: '3.11'
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: ""